Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PegasusPetshop.Models;
using PegasusPetshop.Repository;

namespace PegasusPetshop.Controllers;

public class ClientsController : Controller
{
    private readonly IClienteRepository  _petshopRepository;
    public ClientsController(IClienteRepository petshopRepository) // mudar de acordo com a interface do dado
    {
        _petshopRepository = petshopRepository;
    }


    public IActionResult IndexClientes() // clientes
    {
        List<ClienteModel> cliente = _petshopRepository.listarClientes();
        return View(cliente);
    }

     public IActionResult Criar()
    {
        return View();
    }

     public IActionResult Editar(int id)
    {
        var cliente = _petshopRepository.buscarId(id);
        return View(cliente);
    }

    public IActionResult Deletar(int id){
        _petshopRepository.deletar(id);
        return RedirectToAction("IndexClientes");
    }

    public IActionResult VerificarDeletar(int id)
    {
        var cliente = _petshopRepository.buscarId(id);
        return View(cliente);
    }
    
    [HttpPost] // annotation para realizar os posts
    public IActionResult Criar(ClienteModel cliente){
        _petshopRepository.adicionar(cliente);
        return RedirectToAction("IndexClientes");
    }

    [HttpPost] // annotation para realizar os posts
    public IActionResult Atualizar(ClienteModel cliente){
        _petshopRepository.atualizar(cliente);
        return RedirectToAction("IndexClientes");
    }
}

Controllers/PetsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PegasusPetshop.Models;
using PegasusPetshop.Repository;

namespace PegasusPetshop.Controllers;

public class PetsController : Controller
{
    private readonly IPetsRepository  _petshopRepository;
    public PetsController(IPetsRepository petshopRepository)
    {
        _petshopRepository = petshopRepository;
    }


    public IActionResult IndexPets() //pets
    {
        List<PetsModel> pet = _petshopRepository.listarPets();
        return View(pet);
    }

     public IActionResult Criar()
    {
        return View();
    }

     public IActionResult Editar(int id)
    {
        var pet = _petshopRepository.buscarId(id);
        return View(pet);
    }

    public IActionResult Deletar(int id){
        _petshopRepository.deletar(id);
        return RedirectToAction("IndexPets");
    }

    public IActionResult VerificarDeletar(int id)
    {
        var pet = _petshopRepository.buscarId(id);
        return View(pet);
    }
    
    [HttpPost] // annotation para realizar os posts
    public IActionResult Criar(PetsModel pet){
        _petshopRepository.adicionar(pet);
        return RedirectToAction("IndexPets");
    }

    [HttpPost] // annotation para realizar os posts
    public IActionResult Atualizar(PetsModel pet){
        _petshopRepository.atualizar(pet);
        return RedirectToAction("IndexPets");
    }
}

Controllers/PetshopController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PegasusPetshop.Models;
using PegasusPetshop.Repository;

namespace PegasusPetshop.Controllers;

public class PetshopController : Controller
{
    private readonly IPetshopRepository  _petshopRepository;
    public PetshopController(IPetshopRepository petshopRepository)
    {
        _petshopRepository = petshopRepository;
    }

    public IActionResult Index() // funcionarios
    {
        List<PetshopModel> funcionario = _petshopRepository.listarFuncionarios();
        return View(funcionario);
    }


     public IActionResult Criar()
    {
        return View();
    }

    public IActionResult Escolha()
    {
        return View();
    }

    public IActionResult EscolhaExibir()
    {
        return View();
    }

     public IActionResult Editar(int id)
    {
        var funcionario = _petshopRepository.buscarId(id);
        return View(funcionario);
    }

    public IActionResult Deletar(int id){
        _petshopRepository.deletar(id);
        return RedirectToAction("Index");
    }

    public IActionResult VerificarDeletar(int id)
    {
        var funcionario = _petshopRepository.buscarId(id);
        return View(funcionario); // COLOQUEI DE VOLTA O FUNCIONARIO E COMEÇOU A DELETAR
    }
    
    [HttpPost] // annotation para realizar os posts
    public IActionResult Criar(PetshopModel funcionario){
        if (ModelState.IsValid)
        {

            _petshopRepository.adicionar(funcionario);
            return RedirectToAction("Index");   
        }
        return View("Criar");
    }

    [HttpPost] // annotation para realizar os posts
    public IActionResult Atualizar(PetshopModel funcionario){
        if (ModelState.IsValid)
        {
            _petshopRepository.atualizar(funcionario);
            return RedirectToAction("Index");
        }
        return View("Editar");
    }
}

Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PegasusPetshop.Models;
using PegasusPetshop.Repository;

namespace PegasusPetshop.Controllers; // CASO DE ALGUM ERRO DEPOIS, COLOQUE DE VOLTA NO LUGAR DE _produtoRepository

public class ProductsController : Controller
{
    private readonly IProdutosRepository  _produtoRepository;
    public ProductsController(IProdutosRepository produtosRepository)
    {
        _produtoRepository = produtosRepository;
    }


    public IActionResult IndexProdutos() // produtos
    {
        List<ProdutoModel> produto = _produtoRepository.listarProdutos();
        return View(produto);
    }

     public IActionResult Criar()
    {
        return View();
    }

     public IActionResult Editar(int id)
    {
        var produto = _produtoRepository.buscarId(id);
        return View(produto);
    }

    public IActionResult Deletar(int id){
        _produtoRepository.deletar(id);
        return RedirectToAction("IndexProdutos");
    }

    public IActionResult VerificarDeletar(int id)
    {
        var produto = _produtoRepository.buscarId(id);
        return View(produto);
    }
    
    [HttpPost] // annotation para realizar os posts
    public IActionResult Criar(ProdutoModel produto){
        _produtoRepository.adicionar(produto);
        return RedirectToAction("IndexProdutos");
    }

    [HttpPost] // annotation para realizar os posts
    public IActionResult Atualizar(ProdutoModel produto){
        _produtoRepository.atualizar(produto);
        return RedirectToAction("IndexProdutos");
    }
}

Views/Petshop/Criar.cshtml
@model PetshopModel
@{
    ViewData["Title"] = "Página de Funcionarios";
}
<div class="text-center">
    <h1 class="display-4">Adicionar Funcionario</h1>
</div>

<form method="post" asp-controller="Petshop" asp-action="Criar">

    <div class="mb-3">
        <label for="nome">Nome</label>
        <input type="text" class="form-control" asp-for="Nome" id="nome" placeholder="Insira o nome" required>
        @Html.ValidationMessageFor(x => x.Nome)
    </div>

    <div class="mb-3">
        <label for="genero">Gênero</label>
        <input type="text" class="form-control" asp-for="Genero" id="nome" placeholder="M ou F" required>
        @Html.ValidationMessageFor(x => x.Genero)
    </div>

    <div class="mb-3">
        <label for="cargo">Cargo</label>
        <input type="text" class="form-control" asp-for="Cargo" id="email" placeholder="Ex: Admnistrador, Vendedor, Banhista, Tosador, Veterinário, Recepcionista" required>
        @Html.ValidationMessageFor(x => x.Cargo)
    </div>

    <div class="mb-3">
        <label for="salario">Salario</label>
        <input type="text" class="form-control" asp-for="Salario" id="email" placeholder="R$ 0000.00" required>
        @Html.ValidationMessageFor(x => x.Salario)
    </div>

    <div class="mb-3">
        <label for="telefone">Contato</label>
        <input type="text" class="form-control" asp-for="Contato" id="telefone" placeholder="(XX) X XXXX-XXXX" required>
        @Html.ValidationMessageFor(x => x.Contato)
    </div>

    <div class="mb-3">
        <label for="email">E-mail</label>
        <input type="text" class="form-control" asp-for="Email" id="email" placeholder="Insira o e-mail" required>
        @Html.ValidationMessageFor(x => x.Email)
    </div>

        <div class="mb-3">
        <label for="endereco">Endereço</label>
        <input type="text" class="form-control" asp-for="Endereco" id="email" placeholder="Insira o endereço" required>
        @Html.ValidationMessageFor(x => x.Endereco)
    </div>

    <button type="submit" class="btn btn-primary">Criar</button>
    <a role="submit" class="btn btn-secondary" asp-controller="Petshop" asp-action="Escolha">Voltar</a>
</form>

Views/Petshop/Editar.cshtml
@model PetshopModel

@{
    ViewData["Title"] = "Página de Funcionarios";
}
<div class="text-center">
    <h1 class="display-4">Editar Funcionario</h1>
 
</div>

<!-- AQUI TIRA TODOS OS ASP FOR -->
<form method="post" asp-controller="Petshop" asp-action="Atualizar">
    <input type="hidden" asp-for="Id"/>
    <div class="mb-3">
        <label for="nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" id="nome" placeholder="Insira o nome" required>
        @Html.ValidationMessageFor(x => x.Nome)
    </div>

    <div class="mb-3">
        <label for="genero">Gênero</label>
        <input type="text" asp-for="Genero" class="form-control" id="nome" placeholder="M ou F" required>
        @Html.ValidationMessageFor(x => x.Genero)
    </div>

    <div class="mb-3">
        <label for="cargo">Cargo</label>
        <input type="text" asp-for="Cargo" class="form-control" id="email" placeholder="Ex: Admnistrador, Vendedor, Banhista, Tosador, Veterinário, Recepcionista" required>
        @Html.ValidationMessageFor(x => x.Cargo)
    </div>

    <div class="mb-3">
        <label for="salario">Salario</label>
        <input type="text" asp-for="Salario" class="form-control" id="email" placeholder="R$ 0000.00" required>
        @Html.ValidationMessageFor(x => x.Salario)
    </div>

    <div class="mb-3">
        <label for="telefone">Contato</label>
        <input type="text" asp-for="Contato" class="form-control" id="telefone" placeholder="(XX) X XXXX-XXXX" required>
        @Html.ValidationMessageFor(x => x.Contato)
    </div>

    <div class="mb-3">
        <label for="email">E-mail</label>
        <input type="text" asp-for="Email" class="form-control" id="email" placeholder="Insira o e-mail" required>
        @Html.ValidationMessageFor(x => x.Email)
    </div>

    <div class="mb-3">
        <label for="endereco">Endereço</label>
        <input type="text" asp-for="Endereco" class="form-control" id="email" placeholder="Insira o endereço" required>
        @Html.ValidationMessageFor(x => x.Endereco)
    </div>

    <button type="submit" class="btn btn-primary">Alterar</button>
    <a role="submit" class="btn btn-secondary" asp-controller="Petshop" asp-action="Index">Voltar</a>
</form>


Views/Petshop/Escolha.cshtml
@{
    var hora = DateTime.Now.Hour;
    var message = "";
    if (hora >= 6 && hora <= 11)
    {
        message = "Bom Dia";
    }
    else if (hora >= 12 && hora <= 18)
    {
        message = "Boa Tarde";
    }
    else
    {
        message = "Boa Noite";
    }
}

<div class="text-center">
    <h1 class="titles">Olá, @message! Selecione o que cadastrar</h1>
</div>
<ul class="ul-cards-choice">    
    <li class="li-cards-services">
        <div class="container">
            <!-- Card 1 -->
            <div class="card card-1">
                <!-- card-header -->
                <div class="card-header">
                    <img src="https://www.petshop3p.com.br/images/produtos_1.png" class="card-img" />
                </div>

                <div>
                    <!-- card-header -->

                    <!-- card-body -->
                    <div class="card-body">
                        <h3 class="card-local">Produtos</h3>
                        <p class="card-texto">
                            O que seria de nós sem os nossos produtos...
                        </p>
                    </div>
                    <!-- card-body -->

                    <!-- card-footer -->
                    <div class="card-footer">
                        <a asp-area="" asp-controller="Products" asp-action="Criar">Cadastrar</a>
                    </div>
                    <!-- card-footer -->
                </div>
                <!-- Card 1 -->
            </div>
    </li>

    <li class="li-cards-services">
        <div class="container">
            <!-- Card 1 -->
            <div class="card card-1">
                <!-- card-header -->
                <div class="card-header">
                    <img src="https://petshopbusiness.com.br/files/2017/05/funcionarios.jpg" class="card-img" />
                </div>

                <div>
                    <!-- card-header -->

                    <!-- card-body -->
                    <div class="card-body">
                        <h3 class="card-local">Funcionários</h3>
                        <p class="card-texto">
                            Os funcionários são o coração da nossa empresa.
                        </p>
                    </div>
                    <!-- card-body -->

                    <!-- card-footer -->
                    <div class="card-footer">
                        <a asp-area="" asp-controller="Petshop" asp-action="Criar">Cadastrar</a>
                    </div>
                    <!-- card-footer -->
                </div>
                <!-- Card 1 -->
            </div>
    </li>

    <li class="li-cards-services">
        <div class="container">
            <!-- Card 1 -->
            <div class="card card-1">
                <!-- card-header -->
                <div class="card-header">
                    <img src="https://www.dataon.com.br/wp-content/uploads/2021/05/clientes.jpeg" class="card-img" />
                </div>

                <div>
                    <!-- card-header -->

                    <!-- card-body -->
                    <div class="card-body">
                        <h3 class="card-local">Clientes</h3>
                        <p class="card-texto">
                            Os clientes nos enchem de vida a cada visita, seus pets ainda mais.
                        </p>
                    </div>
                    <!-- card-body -->

                    <!-- card-footer -->
                    <div class="card-footer">
                        <a asp-area="" asp-controller="Clients" asp-action="Criar">Cadastrar</a>
                    </div>
                    <!-- card-footer -->
                </div>
                <!-- Card 1 -->
            </div>
    </li>

    <li class="li-cards-services">
        <div class="container">
            <!-- Card 1 -->
            <div class="card card-1">
                <!-- card-header -->
                <div class="card-header">
                    <img src="https://petaporterco.com.br/wp-content/uploads/2022/02/petshop-de-luxo.jpg" class="card-img" />
                </div>

                <div>
                    <!-- card-header -->

                    <!-- card-body -->
                    <div class="card-body">
                        <h3 class="card-local">Pets</h3>
                        <p class="card-texto">
                            Pets, quem não ama nossos bichinhos ?
                        </p>
                    </div>
                    <!-- card-body -->

                    <!-- card-footer -->
                    <div class="card-footer">
                        <a asp-area="" asp-controller="Pets" asp-action="Criar">Cadastrar</a>
                    </div>
                    <!-- card-footer -->
                </div>
                <!-- Card 1 -->
            </div>
    </li>
</ul>


Views/Petshop/EscolhaExibir.cshtml
@{
    var hora = DateTime.Now.Hour;
    var message = "";
    if (hora >= 6 && hora <= 11)
    {
        message = "Bom Dia";
    }
    else if (hora >= 12 && hora <= 18)
    {
        message = "Boa Tarde";
    }
    else
    {
        message = "Boa Noite";
    }
}

<div class="text-center">
    <h1 class="titles">Olá, @message! Selecione o que exibir</h1>
</div>
<ul class="ul-cards-choice">    
    <li class="li-cards-services">
        <div class="container">
            <!-- Card 1 -->
            <div class="card card-1">
                <!-- card-header -->
                <div class="card-header">
                    <img src="https://www.petshop3p.com.br/images/produtos_1.png" class="card-img" />
                </div>

                <div>
                    <!-- card-header -->

                    <!-- card-body -->
                    <div class="card-body">
                        <h3 class="card-local">Produtos</h3>
                        <p class="card-texto">
                            O que seria de nós sem os nossos produtos...
                        </p>
                    </div>
                    <!-- card-body -->

                    <!-- card-footer -->
                    <div class="card-footer">
                        <a asp-area="" asp-controller="Products" asp-action="IndexProdutos">Exibir</a>
                    </div>
                    <!-- card-footer -->
                </div>
                <!-- Card 1 -->
            </div>
    </li>

    <li class="li-cards-services">
        <div class="container">
            <!-- Card 1 -->
            <div class="card card-1">
                <!-- card-header -->
                <div class="card-header">
                    <img src="https://petshopbusiness.com.br/files/2017/05/funcionarios.jpg" class="card-img" />
                </div>

                <div>
                    <!-- card-header -->

                    <!-- card-body -->
                    <div class="card-body">
                        <h3 class="card-local">Funcionários</h3>
                        <p class="card-texto">
                            Os funcionários são o coração da nossa empresa.
                        </p>
                    </div>
                    <!-- card-body -->

                    <!-- card-footer -->
                    <div class="card-footer">
                        <a asp-area="" asp-controller="Petshop" asp-action="Index">Exibir</a>
                    </div>
                    <!-- card-footer -->
                </div>
                <!-- Card 1 -->
            </div>
    </li>

    <li class="li-cards-services">
        <div class="container">
            <!-- Card 1 -->
            <div class="card card-1">
                <!-- card-header -->
                <div class="card-header">
                    <img src="https://www.dataon.com.br/wp-content/uploads/2021/05/clientes.jpeg" class="card-img" />
                </div>

                <div>
                    <!-- card-header -->

                    <!-- card-body -->
                    <div class="card-body">
                        <h3 class="card-local">Clientes</h3>
                        <p class="card-texto">
                            Os clientes nos enchem de vida a cada visita, seus pets ainda mais.
                        </p>
                    </div>
                    <!-- card-body -->

                    <!-- card-footer -->
                    <div class="card-footer">
                        <a asp-area="" asp-controller="Clients" asp-action="IndexClientes">Exibir</a>
                    </div>
                    <!-- card-footer -->
                </div>
                <!-- Card 1 -->
            </div>
    </li>

    <li class="li-cards-services">
        <div class="container">
            <!-- Card 1 -->
            <div class="card card-1">
                <!-- card-header -->
                <div class="card-header">
                    <img src="https://petaporterco.com.br/wp-content/uploads/2022/02/petshop-de-luxo.jpg" class="card-img" />
                </div>

                <div>
                    <!-- card-header -->

                    <!-- card-body -->
                    <div class="card-body">
                        <h3 class="card-local">Pets</h3>
                        <p class="card-texto">
                            Pets, quem não ama nossos bichinhos ?
                        </p>
                    </div>
                    <!-- card-body -->

                    <!-- card-footer -->
                    <div class="card-footer">
                        <a asp-area="" asp-controller="Pets" asp-action="IndexPets">Exibir</a>
                    </div>
                    <!-- card-footer -->
                </div>
                <!-- Card 1 -->
            </div>
    </li>
</ul>


Views/Petshop/Estoque.cshtml
<!-- 

CNPJ VARCHAR(20) NOT NULL,
    CONSTRAINT FK_FornecedoresProdutos FOREIGN KEY (CNPJ) REFERENCES Fornecedores (CNPJ),
	ClasseDoProduto VARCHAR(30) NOT NULL, -- exemplo : limpeza, banho, tosa
    Nome VARCHAR(100) NOT NULL,
    Descricao VARCHAR(200) NOT NULL,
    ValorDeCompra DECIMAL(7,2) NOT NULL,
    ValorDeVenda DECIMAL(7,2) NOT NULL,
    DataDeEntrada DATE NOT NULL,
    DataDeFabricacao DATE NOT NULL,
    DataDeValidade DATE NOT NULL, 
    Lote INT(5) NOT NULL,
	CodigoDeBarra INT(18) PRIMARY KEY NOT NULL, -- data e ano de chegada (ex: 20020325) + lote (ex:A22) + id do produto (ex: 1, 2, 3) 
    Peso DECIMAL(7,2) DEFAULT NULL,
    QuantidadeEmEstoque INT(100) NOT NULL, -- MAXIMO 900
    QuantidadeMinima INT(100) NOT NULL -- MINIMO 150    
-->

@model List<PetshopModel>
<div class="text-center">
    <h2>Estoque de produtos</h2>
   
    <br>

    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-outline-primary" role="button" asp-controller="Petshop" asp-action="Criar">Adicionar Funcionario</a>
    </div>

    <br>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">#Codigo de barra</th>
                <th scope="col">CNPJ</th>
                <th scope="col">Nome</th>
                <th scope="col">Classe</th>
                <th scope="col">Valor</th>
                <th scope="col">Data de validade</th>
                <th scope="col">Quantidade em estoque</th>     
            </tr>
        </thead>
        <tbody>
            @if(Model != null && Model.Any()){
               int i = 1;
                foreach(PetshopModel funcionario in Model){
                    <tr>
                        <th scope="row">@i</th>
                        <td>@funcionario.Nome</td>

                        <td>@funcionario.Genero</td>

                        <td>@funcionario.Cargo</td>

                        <td>@funcionario.Salario</td>

                        <td>@funcionario.Contato</td>

                        <td>@funcionario.Email</td>

                        <td>@funcionario.Endereco</td>

                        <td>
                            <a role="button" class="btn btn-primary" asp-route-Id="@funcionario.Id" asp-controller="Petshop" asp-action="Editar">Editar</a>
                            <a role="button" class="btn btn-danger"  asp-controller="Petshop" asp-action="VerificarDeletar">Deletar</a>
                        </td>
                    </tr>    
                    i++;     
                }
            }
        </tbody>
    </table>
</div>

Views/Petshop/Index.cshtml
@model List<PetshopModel>

<div class="text-center">
    <h2>Lista de Funcionários</h2>
   
    <br>

    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-outline-primary" role="button" asp-controller="Petshop" asp-action="Criar">Adicionar Funcionario</a>
    </div>

    <br>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Gênero</th>
                <th scope="col">Cargo</th>
                <th scope="col">Salário</th>
                <th scope="col">Contato</th>
                <th scope="col">E-mail</th>
                <th scope="col">Endereco</th>      
            </tr>
        </thead>
        <tbody>
            @if(Model != null && Model.Any()){
               int i = 1;
                foreach(PetshopModel funcionario in Model){
                    <tr>
                        <th scope="row">@i</th>
                        <td>@funcionario.Nome</td>

                        <td>@funcionario.Genero</td>

                        <td>@funcionario.Cargo</td>

                        <td>@funcionario.Salario</td>

                        <td>@funcionario.Contato</td>

                        <td>@funcionario.Email</td>

                        <td>@funcionario.Endereco</td>

                        <td>
                            <a role="button" class="btn btn-primary" asp-route-id="@funcionario.Id" asp-controller="Petshop" asp-action="Editar">Editar</a>
                            <a role="button" class="btn btn-danger" asp-route-id="@funcionario.Id" asp-controller="Petshop" asp-action="VerificarDeletar">Deletar</a>
                        </td>
                    </tr>    
                    i++;     
                }
            }
        </tbody>
    </table>
</div>

Views/Petshop/VerificarDeletar.cshtml
@model PetshopModel

@{
    ViewData["Title"] = "Página de Funcionários";
}
<div class="text-center">
    <h1 class="display-4">Realmente deseja Deletar O Usuário (@Model.Nome)?</h1>
    <td>
        <a role="button" class="btn btn-danger" asp-route-id="@Model.Id" asp-controller="Petshop" asp-action="Deletar">Confirmar</a> <!-- BUG FIXING : Mude o nome da action caso dê problema ou então vá na controller digite ctrl + F e digite "var funcionario" que o comentario lá irá ajudar -->
        <a role="button" class="btn btn-secondary" asp-controller="Petshop" asp-action="Index">Voltar</a>
    </td>
</div>